name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3', '3.4' ]
        database: [ 'mysql', 'postgresql', 'sqlite' ]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: gutentag
          POSTGRES_DB: gutentag
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: gutentag
          MYSQL_DATABASE: gutentag
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Generate Appraisal gemfiles
        run: bundle exec appraisal generate
      - name: Install gems for each appraisal
        run: bundle exec appraisal install
      - name: Test
        env:
          CI: "true"
          DATABASE: ${{ matrix.database }}
          DB_USERNAME: root
          DB_PASSWORD: gutentag
          DB_HOST: 127.0.0.1
        run: bundle exec appraisal rspec

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
